import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"
import { AnalysisResult, Subscription } from "./types"

export function exportToCSV(data: AnalysisResult) {
    const headers = ["Name", "Amount", "Currency", "Frequency", "Category", "Status", "Last Payment"]
    const rows = data.subscriptions.map(sub => [
        sub.name,
        sub.amount.toFixed(2),
        sub.currency,
        sub.frequency,
        sub.category,
        sub.status,
        sub.lastPaymentDate
    ])

    const csvContent = [
        headers.join(","),
        ...rows.map(row => row.join(","))
    ].join("\n")

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.setAttribute("href", url)
    link.setAttribute("download", `subscription_audit_${new Date().toISOString().split('T')[0]}.csv`)
    link.style.visibility = 'hidden'
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
}

export function exportToPDF(data: AnalysisResult) {
    const doc = new jsPDF()

    // Header
    doc.setFontSize(22)
    doc.setTextColor(40, 40, 40)
    doc.text("Subscription Audit Report", 14, 22)

    doc.setFontSize(11)
    doc.setTextColor(100, 100, 100)
    doc.text(`Generated on ${new Date().toLocaleDateString()}`, 14, 30)

    // Summary Box
    doc.setDrawColor(200, 200, 200)
    doc.rect(14, 40, 182, 30)

    doc.setFontSize(10)
    doc.text("Total Monthly Spend", 20, 50)
    doc.setFontSize(14)
    doc.setTextColor(0, 0, 0)
    doc.text(`$${data.totalMonthlySpend.toFixed(2)}`, 20, 60)

    doc.setFontSize(10)
    doc.setTextColor(100, 100, 100)
    doc.text("Potential Yearly Savings", 100, 50)
    doc.setFontSize(14)
    doc.setTextColor(0, 150, 0)
    doc.text(`$${data.yearlyProjection.toFixed(2)}`, 100, 60)

    // Table
    const tableData = data.subscriptions.map(sub => [
        sub.name,
        sub.category,
        `$${sub.amount.toFixed(2)}`,
        sub.frequency,
        sub.lastPaymentDate
    ])

    autoTable(doc, {
        startY: 80,
        head: [['Subscription', 'Category', 'Cost', 'Frequency', 'Last Bill']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [66, 66, 66] },
        styles: { fontSize: 10, cellPadding: 3 },
    })

    // Footer
    const pageCount = doc.internal.pages.length - 1
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFontSize(8)
        doc.setTextColor(150)
        doc.text(`Page ${i} of ${pageCount} - Generated by SubscriptionSlayer`, 14, doc.internal.pageSize.height - 10)
    }

    doc.save(`subscription_audit_${new Date().toISOString().split('T')[0]}.pdf`)
}
