import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs))
}

export function formatCurrency(amount: number, currency: string = "USD"): string {
    const localeMap: Record<string, string> = {
        "IDR": "id-ID",
        "USD": "en-US",
        "EUR": "de-DE", // or en-IE, de-DE uses comma for decimal which is standard for Euro
        "GBP": "en-GB"
    };

    const locale = localeMap[currency] || "en-US";

    return new Intl.NumberFormat(locale, {
        style: "currency",
        currency: currency,
        minimumFractionDigits: currency === "IDR" ? 0 : 2,
        maximumFractionDigits: currency === "IDR" ? 0 : 2
    }).format(amount)
}

export function formatCompactCurrency(amount: number, currency: string = "USD"): string {
    if (currency === "IDR") {
        if (amount >= 1000000000) return `Rp ${(amount / 1000000000).toFixed(1)}M`; // Miliar
        if (amount >= 1000000) return `Rp ${(amount / 1000000).toFixed(1)}jt`;
        if (amount >= 1000) return `Rp ${(amount / 1000).toFixed(0)}rb`;
        return `Rp ${amount}`;
    }

    const localeMap: Record<string, string> = {
        "USD": "en-US",
        "EUR": "de-DE",
        "GBP": "en-GB"
    };
    const locale = localeMap[currency] || "en-US";

    return new Intl.NumberFormat(locale, {
        style: "currency",
        currency: currency,
        notation: "compact",
        maximumFractionDigits: 1
    }).format(amount)
}

export function generateGoogleCalendarLink(name: string, cost: string, date: Date): string {
    const startDate = date.toISOString().replace(/-|:|\.\d\d\d/g, ""); // Format: YYYYMMDDTHHMMSSZ
    const endDate = new Date(date.getTime() + 30 * 60 * 1000).toISOString().replace(/-|:|\.\d\d\d/g, ""); // +30 mins

    const details = `Reminder to cancel or review your ${name} subscription.\nCost: ${cost}\n\nGenerated by Subscription Slayer.`;
    const params = new URLSearchParams({
        action: "TEMPLATE",
        text: `Cancel Subscription: ${name}`,
        dates: `${startDate}/${endDate}`,
        details: details,
    });

    return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

export function downloadICSFile(name: string, cost: string, date: Date) {
    const startDate = date.toISOString().replace(/-|:|\.\d\d\d/g, "");
    const endDate = new Date(date.getTime() + 30 * 60 * 1000).toISOString().replace(/-|:|\.\d\d\d/g, "");

    const icsContent = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        "PRODID:-//Subscription Slayer//EN",
        "BEGIN:VEVENT",
        `UID:${Date.now()}@subscriptionslayer.app`,
        `DTSTAMP:${startDate}`,
        `DTSTART:${startDate}`,
        `DTEND:${endDate}`,
        `SUMMARY:Cancel Subscription: ${name}`,
        `DESCRIPTION:Reminder to cancel or review your ${name} subscription.\\nCost: ${cost}\\n\\nGenerated by Subscription Slayer.`,
        "END:VEVENT",
        "END:VCALENDAR"
    ].join("\r\n");

    const blob = new Blob([icsContent], { type: "text/calendar;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `cancel-${name.toLowerCase().replace(/\s+/g, '-')}.ics`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}
